use crate::{
    process,
    render::{self, Build, Manifest},
    storage::*,
};
use anyhow::{Context, Result, ensure};
use chrono::Utc;
use std::{collections::BTreeMap, fs, path::Path, time::Duration};

fn git(path: &Path, args: &[&str]) -> Result<String> {
    let mut a = vec![
        "-c",
        "core.hooksPath=/dev/null",
        "-c",
        "credential.helper=",
        "-c",
        "credential.helper=!gh auth git-credential",
        "-c",
        "protocol.file.allow=never",
    ];
    a.extend(args);
    process::run("git", &a, Some(path), Duration::from_secs(60))
}
fn gh(args: &[&str]) -> Result<String> {
    process::run("gh", args, None, Duration::from_secs(45))
}
pub fn valid_repository(name: &str) -> Result<()> {
    let p: Vec<_> = name.split('/').collect();
    ensure!(
        p.len() == 2
            && p.iter().all(|s| !s.is_empty()
                && !s.starts_with('.')
                && s.bytes()
                    .all(|c| c.is_ascii_alphanumeric() || b"-_ .".contains(&c))
                && !s.contains(' ')),
        "Repository must be owner/name"
    );
    Ok(())
}
fn valid_branch(branch: &str) -> Result<()> {
    ensure!(
        !branch.is_empty()
            && !branch.starts_with('-')
            && !branch.starts_with('.')
            && branch
                .bytes()
                .all(|c| c.is_ascii_alphanumeric() || b"-_/".contains(&c))
            && !branch.ends_with('/')
            && !branch.contains("//"),
        "Invalid deployment branch"
    );
    Ok(())
}
fn remote(s: &Snapshot) -> Result<String> {
    valid_repository(&s.config.deploy.repository)?;
    valid_branch(&s.config.deploy.branch)?;
    Ok(format!(
        "https://github.com/{}.git",
        s.config.deploy.repository
    ))
}
fn remote_head(root: &Path, url: &str, branch: &str) -> Result<String> {
    let out = git(
        root,
        &["ls-remote", "--heads", url, &format!("refs/heads/{branch}")],
    )?;
    let sha = out.split_whitespace().next().unwrap_or("");
    ensure!(
        sha.is_empty() || sha.len() == 40 && sha.bytes().all(|b| b.is_ascii_hexdigit()),
        "Invalid remote head"
    );
    Ok(sha.into())
}
pub fn github_status() -> Result<serde_json::Value> {
    gh(&["auth", "status", "--hostname", "github.com"])?;
    let user: serde_json::Value = serde_json::from_str(&gh(&["api", "user"])?)?;
    Ok(serde_json::json!({"login":user["login"],"authenticated":true}))
}
pub fn repositories() -> Result<serde_json::Value> {
    Ok(serde_json::from_str(&gh(&[
        "repo",
        "list",
        "--limit",
        "100",
        "--json",
        "nameWithOwner,isPrivate,url",
    ])?)?)
}
pub fn setup(
    root: &Path,
    expected: &str,
    repository: &str,
    create: bool,
) -> Result<serde_json::Value> {
    let _lock = lock(root)?;
    let s = snapshot(root)?;
    s.expected(expected)?;
    valid_repository(repository)?;
    let account = github_status()?;
    if create {
        gh(&[
            "repo",
            "create",
            repository,
            "--public",
            "--description",
            "Static publication generated by OmaPress",
        ])?;
    }
    let v: serde_json::Value =
        serde_json::from_str(&gh(&["api", &format!("repos/{repository}")])?)?;
    ensure!(
        v["permissions"]["push"].as_bool() == Some(true),
        "You need push permission to the destination"
    );
    Ok(
        serde_json::json!({"repository":repository,"private":v["private"],"account":account,"message":"Save this repository in publication settings. Pages is enabled after the first reviewed deployment."}),
    )
}
pub fn plan(root: &Path, expected: &str) -> Result<serde_json::Value> {
    let s = snapshot(root)?;
    s.expected(expected)?;
    let ledger = state(root)?;
    ensure!(
        ledger.pending.is_none(),
        "A deployment is unresolved; recheck it first"
    );
    let b = render::build(&s, &ledger, false)?;
    let url = remote(&s)?;
    github_status()?;
    let head = remote_head(root, &url, &s.config.deploy.branch)?;
    Ok(
        serde_json::json!({"source_hash":s.hash,"output_hash":b.manifest.output_hash,"repository":s.config.deploy.repository,"branch":s.config.deploy.branch,"expected_remote_head":head,"article_ids":b.manifest.articles.keys().collect::<Vec<_>>(),"base_url":s.config.base_url,"source_commit":git(root,&["rev-parse","HEAD"]).ok().map(|v|v.trim().to_owned())}),
    )
}
fn cache_build(root: &Path, id: &str, files: &BTreeMap<String, Vec<u8>>) -> Result<()> {
    let dir = safe_path(root, &format!(".omapress/deployments/{id}"))?;
    ensure!(!dir.exists(), "Deployment ID already exists");
    fs::create_dir_all(&dir)?;
    for (p, b) in files {
        atomic_write(&safe_path(&dir, p)?, b)?;
    }
    Ok(())
}
fn output_from_cache(root: &Path, d: &Deployment) -> Result<BTreeMap<String, Vec<u8>>> {
    let dir = safe_path(root, &format!(".omapress/deployments/{}", d.id))?;
    let bytes = read_bounded(&safe_path(&dir, "build-manifest.json")?, 8 * 1024 * 1024)?;
    let manifest: Manifest = serde_json::from_slice(&bytes)?;
    ensure!(
        manifest.output_hash == d.output_hash && !manifest.private_preview,
        "Invalid cached deployment manifest"
    );
    let mut files = BTreeMap::new();
    for (p, h) in &manifest.files {
        let b = read_bounded(&safe_path(&dir, p)?, 32 * 1024 * 1024)?;
        ensure!(&hash(&b) == h, "Cached output hash mismatch: {p}");
        files.insert(p.clone(), b);
    }
    ensure!(
        tree_hash(&files) == d.output_hash,
        "Cached output tree mismatch"
    );
    files.insert("build-manifest.json".into(), bytes);
    render::feed_check_files(&files)?;
    Ok(files)
}
fn stage_commit(s: &Snapshot, files: &BTreeMap<String, Vec<u8>>, previous: &str) -> Result<String> {
    let work = safe_path(&s.root, ".omapress/deploy-worktree")?;
    if work.exists() {
        // Preserve unexpected user edits rather than clearing a worktree.
        ensure!(
            git(&work, &["status", "--porcelain"])?.trim().is_empty(),
            "Generated deployment worktree is dirty; inspect it before continuing"
        );
        fs::remove_dir_all(&work)?;
    }
    fs::create_dir(&work)?;
    git(&work, &["init", "--quiet"])?;
    let url = remote(s)?;
    if !previous.is_empty() {
        git(&work, &["fetch", "--quiet", "--depth", "1", &url, previous])?;
        git(&work, &["checkout", "--quiet", "--detach", "FETCH_HEAD"])?;
        git(&work, &["rm", "-r", "--ignore-unmatch", "."])?;
    }
    for (p, b) in files {
        atomic_write(&safe_path(&work, p)?, b)?;
    }
    git(&work, &["add", "--all"])?;
    git(
        &work,
        &[
            "-c",
            "user.name=OmaPress",
            "-c",
            "user.email=omapress@users.noreply.github.com",
            "commit",
            "--quiet",
            "--allow-empty",
            "-m",
            "Publish reviewed OmaPress output",
        ],
    )?;
    Ok(git(&work, &["rev-parse", "HEAD"])?.trim().into())
}
pub fn publish(root: &Path, expected: &str, expected_remote: &str) -> Result<serde_json::Value> {
    let _lock = lock(root)?;
    let s = snapshot(root)?;
    s.expected(expected)?;
    let mut ledger = state(root)?;
    ensure!(
        ledger.pending.is_none(),
        "A deployment is unresolved; recheck it first"
    );
    let b = render::build(&s, &ledger, false)?;
    dispatch(&s, &mut ledger, b, expected_remote)
}
fn dispatch(
    s: &Snapshot,
    ledger: &mut State,
    b: Build,
    expected_remote: &str,
) -> Result<serde_json::Value> {
    let url = remote(s)?;
    github_status()?;
    ensure!(
        remote_head(&s.root, &url, &s.config.deploy.branch)? == expected_remote,
        "Remote branch moved after review; prepare a new deployment plan"
    );
    let id = uuid::Uuid::new_v4().to_string();
    cache_build(&s.root, &id, &b.files)?;
    let commit = stage_commit(s, &b.files, expected_remote)?;
    snapshot(&s.root)?.expected(&s.hash)?;
    let d = Deployment {
        id,
        repository: s.config.deploy.repository.clone(),
        branch: s.config.deploy.branch.clone(),
        base_url: s.config.base_url.clone(),
        source_hash: s.hash.clone(),
        source_commit: git(&s.root, &["rev-parse", "HEAD"])
            .ok()
            .map(|v| v.trim().into()),
        source_tree: git(&s.root, &["rev-parse", "HEAD^{tree}"])
            .ok()
            .map(|v| v.trim().into()),
        output_hash: b.manifest.output_hash,
        remote_commit: commit.clone(),
        previous_head: expected_remote.into(),
        articles: b.manifest.articles,
        identities: b.identities,
        feeds: b.manifest.feeds,
        created_at: Utc::now().to_rfc3339(),
        verified_at: None,
    };
    ledger.pending = Some(d);
    save_state(&s.root, ledger)?;
    // Exact lease: an absent branch must still be absent, and an existing branch
    // must still have the reviewed head. This never overwrites another writer.
    let lease = format!(
        "--force-with-lease=refs/heads/{}:{expected_remote}",
        s.config.deploy.branch
    );
    let target = format!("{commit}:refs/heads/{}", s.config.deploy.branch);
    if let Err(e) = git(
        &safe_path(&s.root, ".omapress/deploy-worktree")?,
        &["push", &lease, &url, &target],
    ) {
        return Ok(
            serde_json::json!({"status":"unknown","message":format!("Push outcome requires recheck: {e}"),"deployment":ledger.pending}),
        );
    }
    let pages = enable_pages(&s.config.deploy.repository, &s.config.deploy.branch);
    match verify_pending(&s.root, ledger) {
        Ok(v) => Ok(v),
        Err(e) => Ok(
            serde_json::json!({"status":"unknown","message":format!("Remote commit pushed; public verification pending: {e}. Pages setup: {}",pages.err().map(|e|e.to_string()).unwrap_or_else(||"configured".into())),"deployment":ledger.pending}),
        ),
    }
}
fn enable_pages(repo: &str, branch: &str) -> Result<()> {
    let endpoint = format!("repos/{repo}/pages");
    // Existing sites are inspected and preserved; never overwrite another Pages configuration.
    match gh(&["api", &endpoint]) {
        Ok(json) => {
            let v: serde_json::Value = serde_json::from_str(&json)?;
            ensure!(
                v["source"]["branch"] == branch && v["source"]["path"] == "/",
                "Existing Pages configuration uses a different source; configure the reviewed branch manually"
            );
            Ok(())
        }
        Err(e) if e.to_string().contains("404") => {
            gh(&[
                "api",
                "--method",
                "POST",
                &endpoint,
                "-f",
                &format!("source[branch]={branch}"),
                "-f",
                "source[path]=/",
            ])?;
            Ok(())
        }
        Err(e) => Err(e),
    }
}
fn verify_pending(root: &Path, ledger: &mut State) -> Result<serde_json::Value> {
    let d = ledger
        .pending
        .clone()
        .context("No deployment requires recheck")?;
    let url = format!("https://github.com/{}.git", d.repository);
    let head = remote_head(root, &url, &d.branch)?;
    if head == d.previous_head {
        ledger.pending = None;
        save_state(root, ledger)?;
        return Ok(
            serde_json::json!({"status":"not_published","message":"The reviewed push is not present. The article remains Ready; prepare a new deployment plan before retrying."}),
        );
    }
    ensure!(
        head == d.remote_commit,
        "Remote head differs from the pending deployment; no automatic retry or overwrite is safe"
    );
    let manifest_url = format!("{}/build-manifest.json", d.base_url.trim_end_matches('/'));
    let text = process::run(
        "curl",
        &[
            "--fail",
            "--silent",
            "--show-error",
            "--location",
            "--max-redirs",
            "3",
            "--proto",
            "=https,http",
            "--proto-redir",
            "=https,http",
            "--connect-timeout",
            "5",
            "--max-time",
            "15",
            "--max-filesize",
            "8388608",
            "--header",
            "Cache-Control: no-cache",
            &manifest_url,
        ],
        None,
        Duration::from_secs(20),
    )?;
    let manifest: Manifest = serde_json::from_str(&text)?;
    ensure!(
        !manifest.private_preview
            && manifest.output_hash == d.output_hash
            && manifest.source_hash == d.source_hash,
        "Public manifest does not yet match this deployment"
    );
    let expected = output_from_cache(root, &d)?;
    // Verify every generated resource by bytes, not merely a marker file.
    for (path, bytes) in expected
        .iter()
        .filter(|(p, _)| *p != "build-manifest.json" && *p != ".nojekyll")
    {
        let out = tempfile::NamedTempFile::new()?;
        let target = format!("{}/{}", d.base_url.trim_end_matches('/'), path);
        process::run(
            "curl",
            &[
                "--fail",
                "--silent",
                "--show-error",
                "--location",
                "--max-redirs",
                "3",
                "--proto",
                "=https,http",
                "--proto-redir",
                "=https,http",
                "--connect-timeout",
                "5",
                "--max-time",
                "15",
                "--max-filesize",
                "33554432",
                "--output",
                out.path().to_str().context("Invalid temporary path")?,
                &target,
            ],
            None,
            Duration::from_secs(20),
        )?;
        ensure!(
            hash(&read_bounded(out.path(), 32 * 1024 * 1024)?) == hash(bytes),
            "Public output differs: {path}"
        );
    }
    let mut verified = d;
    verified.verified_at = Some(Utc::now().to_rfc3339());
    ledger.identities.extend(verified.identities.clone());
    ledger.deployments.push(verified.clone());
    ledger.pending = None;
    save_state(root, ledger)?;
    Ok(serde_json::json!({"status":"published","deployment":verified}))
}
pub fn recheck(root: &Path) -> Result<serde_json::Value> {
    let _lock = lock(root)?;
    let mut ledger = state(root)?;
    match verify_pending(root, &mut ledger) {
        Ok(v) => Ok(v),
        Err(e) => Ok(
            serde_json::json!({"status":"unknown","message":e.to_string(),"deployment":ledger.pending}),
        ),
    }
}
pub fn rollback(
    root: &Path,
    id: &str,
    expected: &str,
    expected_remote: &str,
) -> Result<serde_json::Value> {
    let _lock = lock(root)?;
    let s = snapshot(root)?;
    s.expected(expected)?;
    let mut ledger = state(root)?;
    ensure!(
        ledger.pending.is_none(),
        "Resolve the pending deployment before rollback"
    );
    let old = ledger
        .deployments
        .iter()
        .find(|d| d.id == id)
        .context("Verified deployment not found")?
        .clone();
    ensure!(
        old.repository == s.config.deploy.repository
            && old.branch == s.config.deploy.branch
            && old.base_url == s.config.base_url,
        "Rollback target differs from publication settings"
    );
    let files = output_from_cache(root, &old)?;
    // Rollback publishes the old artifact byte-for-byte. Its manifest keeps the
    // original source hash; the journal separately records the current review.
    let id = uuid::Uuid::new_v4().to_string();
    let url = remote(&s)?;
    github_status()?;
    ensure!(
        remote_head(root, &url, &s.config.deploy.branch)? == expected_remote,
        "Remote moved after review"
    );
    cache_build(root, &id, &files)?;
    let commit = stage_commit(&s, &files, expected_remote)?;
    snapshot(root)?.expected(expected)?;
    let mut d = old;
    d.id = id;
    d.previous_head = expected_remote.into();
    d.remote_commit = commit.clone();
    d.created_at = Utc::now().to_rfc3339();
    d.verified_at = None;
    ledger.pending = Some(d);
    save_state(root, &ledger)?;
    let lease = format!(
        "--force-with-lease=refs/heads/{}:{expected_remote}",
        s.config.deploy.branch
    );
    if let Err(e) = git(
        &safe_path(root, ".omapress/deploy-worktree")?,
        &[
            "push",
            &lease,
            &url,
            &format!("{commit}:refs/heads/{}", s.config.deploy.branch),
        ],
    ) {
        return Ok(serde_json::json!({"status":"unknown","message":e.to_string()}));
    }
    match verify_pending(root, &mut ledger) {
        Ok(v) => Ok(v),
        Err(e) => Ok(
            serde_json::json!({"status":"unknown","message":e.to_string(),"deployment":ledger.pending}),
        ),
    }
}
